<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>HealthCare.DbMigrate</RootNamespace>
    <AssemblyName>HealthCare.DbMigrate</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\HealthCare.Infrastructure\HealthCare.Infrastructure.csproj" />
  </ItemGroup>

</Project>
